//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementBoostrap4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomsBooking
    {
        public int BookingID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhone { get; set; }
        public System.DateTime BookingFrom { get; set; }
        public System.DateTime BookingTo { get; set; }
        public int AssignRoomID { get; set; }
        public int NumberOfMembers { get; set; }
        public decimal TotalAmount { get; set; }
    }
}
